name: Release Developer

on:
  workflow_dispatch:
  push:
    branches: [develop]

jobs:
  build:
    uses: ./.github/workflows/build-backend.yml
    with: {}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Install Pulumi CLI
        uses: pulumi/actions@v4

      - name: Login to Pulumi S3 Backend
        run: pulumi login s3://${{ secrets.PULUMI_STATE_BUCKET }}
        working-directory: backend/webhook_nest.main
        env:
          PULUMI_CONFIG_PASSPHRASE: ""

      - name: Select Pulumi Stack
        run: pulumi stack select staging
        working-directory: backend/webhook_nest.main
        env:
          PULUMI_CONFIG_PASSPHRASE: ""

      - name: Deploy with Pulumi
        run: pulumi up --yes
        working-directory: backend/webhook_nest.main
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CONFIG_PASSPHRASE: ""
